### ISSUE TITLE
Overflow when there are a lot of artists

### ISSUE THREAD

**Issue by Teltta** [Socketlike/SpotifyModal#1]
The artist names overflow when there are multiple artists with long names.
![image](https://user-images.githubusercontent.com/92880720/210129555-c1615a06-f39f-4de7-877a-2fdb61e269c5.png)

**Comment by Socketlike** [comment]
Would you mind sending the song link in question here?

**Comment by Teltta** [comment]
https://open.spotify.com/track/5OsotZsU0NgNznvzVTpL8W?si=2e26c0e1a5134a09

here's a couple of other songs that i was able to reproduce the overflow with:
https://open.spotify.com/track/66j2GZdu8DKgpa1p05sYXC?si=b94bcd68e5a34736
https://open.spotify.com/track/0OKHUom3gY9xWago6Y1BKk?si=4b607a26f5ca4c93

**Comment by Socketlike** [comment]
For now I've made the artists list trim out the overflow just like the song title.
I have been trying to add a looping text scroll animation to the list but it's not working out so well (`translateX(-100%)` doesn't go to the end of the list element) .-.

**Comment by Socketlike** [comment]
I have pushed a change to the codebase that adds the animation that I was talking about previously to the song title and the artists list. [Would you mind testing it?](https://github.com/Socketlike/SpotifyModal/releases/nightly)

**Comment by Teltta** [comment]
Sorry for the late response, I just tested it, and it seems to be working though sometimes the artists get cut off instead of the scrolling animation taking place but in my opinion that's not a big problem and would avoid yet another headache on your end.

![image](https://user-images.githubusercontent.com/92880720/210220531-01ed24a6-9d1b-4c37-b70f-ae51818fc2df.png)

**Comment by Socketlike** [comment]
May I close this issue now?

**Comment by Teltta** [comment]
Yea go ahead.
