### ISSUE TITLE
bug: new seekbar broken with Revert Rebrand

### ISSUE THREAD

**Issue by MicrocontrollersDev** [Socketlike/SpotifyModal#11]
## Report quality checklist
Please take some time to review this checklist before you continue.  
- [x] I have made sure that this report is **not a duplicate** after searching [this repository's GitHub issues](https://github.com/Socketlike/SpotifyModal/issues)
- [x] This issue **only** happens with this plugin installed

## Describe the bug
When using the [Revert Rebrand](https://replugged.dev/store/dev.replugged.RevertRebrand) theme, the progress bar will start from the middle and expand outwards on both sides.
![DiscordCanary_ebKRs6DaT2](https://github.com/Socketlike/SpotifyModal/assets/66657148/dc72ae37-503b-4bb7-a48c-a6daec4ab46b)

Not sure if this is the theme or plugin's fault, but it did not happen before the seekbar change (1.3.1). Will report on Revert Rebrand if needed.

## Steps to produce
Use Spotify Modal and Revert Rebrand at the same time

## Desired behavior
The progress bar would start from the left and expand to the right

**Comment by Socketlike** [comment]
The new seekbar uses Discord's native slider. RevertRebrand likely had CSS that modifies the slider.

This is not the plugin's fault (the seekbar displays normally without RevertRebrand)

I'm willing to fix this on the plugin side if RevertRebrand doesn't.

**Comment by Socketlike** [comment]
RevertRebrand fixed this issue.
https://github.com/Snare-Hawk/snare-CSS/commit/50af25d860c865d8ed8bc454c1ac64135950ad29
