### ISSUE TITLE
Add fix for Spotify Autopause

### ISSUE THREAD

**Issue by Pukimaa** [Socketlike/SpotifyModal#7]
Basically port this over to Replugged please: https://github.com/BluSpring/Spotify-No-Pause/blob/master/index.js

It can get really annoying and in the original Spotify Plugin it also has that implemented.

**Comment by Socketlike** [comment]
Will get this done ASAP

**Comment by Socketlike** [comment]
I have finished the functionality for disabling auto pause but because I still have a few unfinished features left to do I could not push it upstream today

**Comment by Pukimaa** [comment]
o.O

**Comment by Socketlike** [comment]
I just pushed [v1.2.7](https://github.com/Socketlike/SpotifyModal/releases/v1.2.7) which has the new no Spotify pause feature

**Comment by Pukimaa** [comment]
Great 👍
