### ISSUE TITLE
Local file album art

### ISSUE THREAD

**Issue by aestellic** [Socketlike/SpotifyModal#8]
When playing local files through Spotify Premium, the album art fails to load if it is included in the id3 tags of the music file.

![image](https://user-images.githubusercontent.com/42680119/222934948-cabe32cd-4249-4c7d-8a1c-3114d87bbfbe.png)

**Comment by Socketlike** [comment]
Does the cover art show up on Discord's Spotify rich presence?
If not, I'm pretty sure this is a Spotify API limitation since they don't send local audio files' cover art to their servers -> shows up blank on your RPC

**Comment by aestellic** [comment]
The cover art does not show up on RPC. Could you please update the plugin to prevent blank album art from rendering?

**Comment by Socketlike** [comment]
Will do

**Comment by Socketlike** [comment]
Could you please test the fix for this? It's on the [nightly version](https://github.com/Socketlike/SpotifyModal/releases/nightly).

**Comment by aestellic** [comment]
When starting discord this error appears in the console:
```
8e29d229914e99844730.js:8868 [Replugged:API:Plugins] Error starting plugin SpotifyModal ReferenceError: ct is not defined
    at replugged://plugin/lib.evelyn.SpotifyModal.asar/renderer.js?t=1678588527850}:1
r.<computed> @ 8e29d229914e99844730.js:8868
```

**Comment by Socketlike** [comment]
> When starting discord this error appears in the console:
> 
> ```
> 8e29d229914e99844730.js:8868 [Replugged:API:Plugins] Error starting plugin SpotifyModal ReferenceError: ct is not defined
>     at replugged://plugin/lib.evelyn.SpotifyModal.asar/renderer.js?t=1678588527850}:1
> r.<computed> @ 8e29d229914e99844730.js:8868
> ```

Should be fixed now

**Comment by aestellic** [comment]
I am now getting this error:

```
Replugged:API:Plugins] Error starting plugin SpotifyModal ReferenceError: ct is not defined
    at renderer.js?t=1678590440283}:1
r.<computed> @ 8e29d229914e99844730.js:8868
cn @ (index):1
error @ (index):1
dl @ (index):11
async function (async)
dl @ (index):11
Uh @ (index):11
toggleDisabled @ (index):1
onChange @ 8e29d229914e99844730.js:2803
Ue @ 8e29d229914e99844730.js:1603
Ve @ 8e29d229914e99844730.js:1603
(anonymous) @ 8e29d229914e99844730.js:1624
kr @ 8e29d229914e99844730.js:1624
xr @ 8e29d229914e99844730.js:1624
(anonymous) @ 8e29d229914e99844730.js:1630
cc @ 8e29d229914e99844730.js:1695
De @ 8e29d229914e99844730.js:1602
Yr @ 8e29d229914e99844730.js:1626
Kt @ 8e29d229914e99844730.js:1609
Zt @ 8e29d229914e99844730.js:1609
```

**Comment by Socketlike** [comment]
Have you restarted Discord after installing the nightly version?

**Comment by aestellic** [comment]
Whoops, my bad! It works perfectly now, thanks so much!

**Comment by Socketlike** [comment]
No problem.

**Comment by Socketlike** [comment]
Release [v1.2.9](https://github.com/Socketlike/SpotifyModal/releases/v1.2.9) was released with the fix. Make sure to update.
