### ISSUE TITLE
bug: access token deauthenticate/expire too quickly

### ISSUE THREAD

**Issue by ylw311** [Socketlike/SpotifyModal#9]
## Describe the bug
After a while, or if you restart discord with spotify continuing to play, token becomes unauthenticated and can no longer control from discord.

## Steps to produce
play spotify, close discord and reopen, can't control from modal anymore. Or, allow some time to pass.

## Desired behavior
token is automatically refreshed, and does not expire so quickly 

## temporary fix
reload plugin (but doing this every time is frustrating and tiring)

**Comment by Socketlike** [comment]
Have you tried enabling `Automatic Reauthentication` under `Miscellaneous` in the plugin's settings?

**Comment by ylw311** [comment]
Ah, I think that may fix it. Maybe an idea is to have it checked by default? 
There is also a less critical problem: when I close Discord and reopen it with Spotify running in the background, the modal doesn't appear unless I skip the song to the next. Perhaps this is something to look into - but not as big of a deal I suppose.

**Comment by Socketlike** [comment]
> Ah, I think that may fix it. Maybe an idea is to have it checked by default? 
  
> There is also a less critical problem: when I close Discord and reopen it with Spotify running in the background, the modal doesn't appear unless I skip the song to the next. Perhaps this is something to look into - but not as big of a deal I suppose.
   
I will look into both and they will be fixed in the next-ish update

May I close this now?

**Comment by ylw311** [comment]
Yes, thanks!

**Comment by Socketlike** [comment]
both of them should be resolved now in the [`v1.3.0`](https://github.com/Socketlike/SpotifyModal/releases/tag/v1.3.0) release
